### ISSUE TITLE
异步问题

### ISSUE THREAD

**Issue by wushuangxiaoyu** [linhuaichuan/ecp-uid#1]
https://github.com/linhuaichuan/ecp-uid/blob/485f6c2536de572b13b47e6751288897471f8706/src/main/java/com/myzmds/ecp/core/uid/leaf/SegmentServiceImpl.java#L87

这里 如果是异步的话 不会有问题么？
thresholdHandler() 不会被多次调用？

**Comment by linhuaichuan** [comment]
这边同异步 指的是： 对下一buffer 是否启用异步线程来加载值。 条件已经限制死了当前buffer只会满足一次

**Comment by wushuangxiaoyu** [comment]
为啥限制死了，这里异步执行，释放锁，接着下一个请求来，异步函数还未执行，并且自增也未执行 就会再次进入 thresholdHandler() ?

**Comment by linhuaichuan** [comment]
审视了一下代码，这边的代码确实不严谨。原本采用的是 双重检查的锁来 足够判断是否需要执行thresholdHandler()和fullHandler()，对原子未自增情况欠缺处理。

**Comment by linhuaichuan** [comment]
原子自增堵塞概率非常低，且原子自增 执行时间远低于 解锁执行时间。
在过去2年中，我司使用此工具进行uid处理 还未出现这种情况。

**Comment by wushuangxiaoyu** [comment]
了解 这边是把step调到10 然后再进行压测的，就会出现问题
