### ISSUE TITLE
这里我也有疑惑

### ISSUE THREAD

**Issue by wushuangxiaoyu** [linhuaichuan/ecp-uid#2]
https://github.com/linhuaichuan/ecp-uid/blob/485f6c2536de572b13b47e6751288897471f8706/src/main/java/com/myzmds/ecp/core/uid/leaf/SegmentServiceImpl.java#L96

这里起始cid=0 step=10000,如果同时10001个 请求全部同时过来 ，并且10001通过83行的判断（这里是第一重，没有加锁，这里的cid都是0）然后在原子自增处阻塞 就会超过步长啊,

**Comment by linhuaichuan** [comment]
如举例，第10000个请求过来时，会进入89行max值判断是否进行fullHandler()，
fullHandler() 125行对异步线程的结果进行判断，是否需要切换同步填充下一个buffer，在填充buffer的同时已经对 原子自增进行了重置，所以不会产生超过步长问题。

双buffer策略 支持并发 必须小于 step*2，请根据实际需求设置step。
