### ISSUE TITLE
leaf异步问题

### ISSUE THREAD

**Issue by wushuangxiaoyu** [linhuaichuan/ecp-uid#3]
我觉得 101行 还是有问题 应该加锁 做重试 
我这边是用golang写的：
`s.lock2.Lock()`
	`if atomic.LoadInt64(&s.currentId) == s.segments[s.segIndex()].MaxId {`
		`s.lock2.Unlock()`
		`goto retry`
	`}`
	`id := atomic.AddInt64(&s.currentId, 1)`
	`log.Info("getID from  sucess : %d", id-1)`
	`s.lock2.Unlock()`

**Comment by linhuaichuan** [comment]
没get到你的点。
两次阈值(中间值与最大值)，都使用了重入锁进行了同步控制。
特殊的是：最大阈值检测并只执行一次fullHandler()，保证了已知场景中 新buffer已准备好并进行切换；
                  最大阈值后的新线程的取值，靠外部的重入锁来控制。

**Comment by wushuangxiaoyu** [comment]
>1  if 判断  
  >2     lock
  >3        if判断
  >4  自增
如果初始cid=0, step+1 条请求同时过来，step+1条请求当前持有cid都=0通过了1 的判断，全部打到4 自增这里，这里没有判断重试就会自增 超过buffer
我这里 把step 调到足够小 是会出现这种情况的

**Comment by linhuaichuan** [comment]
十分感谢，了解情况了，我这边重现下。

**Comment by linhuaichuan** [comment]
@wushuangxiaoyu 使用你的思路对方法进行改造， 突入了并发数受step 限制的问题。
测试结果 参见 com.myzmds.ecp.core.uid.idleaf.SegmentServiceImplTest
